name: pre-commit

on:
  pull_request:
  push:
permissions: {}
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 #v6.1.0
    - run: |
        python -m pip install --require-hashes --requirement ${{ github.workspace }}/.github/workflows/pre-commit-requirements.txt
        python -m pip freeze --local
    - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb #v5.0.1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ runner.os }}
    - name: Set SKIP variable for main branch
      if: github.ref == 'refs/heads/main'
      run: echo "SKIP=no-commit-to-branch" >> $GITHUB_ENV
    - run: SKIP="$SKIP" pre-commit run --show-diff-on-failure --color=always --all-files
